-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 16:39:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Farmaciadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Farmaciadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Farmaciadb` DEFAULT CHARACTER SET utf8 ;
USE `Farmaciadb` ;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`TesseraSanitaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`TesseraSanitaria` (
  `CodiceFiscale` VARCHAR(16) NOT NULL,
  `Cognome` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `DataScadenza` DATE NULL,
  `DataEmissione` DATE NULL,
  `DataNascita` DATE NULL,
  `NumeroDocumento` VARCHAR(20) NULL,
  PRIMARY KEY (`CodiceFiscale`))	
  ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `Farmaciadb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Cliente` (
  `CodiceTessera` INT NOT NULL,
  `SaldoPunti` INT NULL,
  `Cellulare` VARCHAR(20) NULL,
  `Consenso` boolean NULL,
  `CodiceFiscale` VARCHAR(16) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Via` VARCHAR(100) NULL,
  `NumeroCivico` VARCHAR(10) NULL,
  `Città` VARCHAR(45) NULL,
  `CAP` VARCHAR(10) NULL,
  PRIMARY KEY (`CodiceTessera`),
  CONSTRAINT `CodiceTessera`
  FOREIGN KEY (`CodiceFiscale`)
	REFERENCES `Farmaciadb`.`TesseraSanitaria` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
	ENGINE = InnoDB
	DEFAULT CHARACTER SET utf8;
    
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`RicettaMedica` (
  `CodiceRicetta` VARCHAR(45) NOT NULL,
  `DataScadenza` DATE NULL,
  `DataEmissione` DATE NULL,
  `CodiceMedicoDibase` VARCHAR(45) NULL,
  `CodiceFiscale` VARCHAR(16) NULL,
  PRIMARY KEY (`CodiceRicetta`),
  -- INDEX `CodiceFiscale_idx` (`CodiceFiscale` ASC) VISIBLE,
  CONSTRAINT `CodiceFiscale`
  FOREIGN KEY (`CodiceFiscale`)
  REFERENCES `Farmaciadb`.`TesseraSanitaria` (`CodiceFiscale`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
    )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Farmaco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Farmaco` (
  `AIC` VARCHAR(50) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `PrincipioAttivo` VARCHAR(45) NULL,
  `PrezzoUnitario` DECIMAL(10,2) NULL,
  `Dosaggio` VARCHAR(45) NULL,
  `FormaFarmaceutica` VARCHAR(45) NULL,
  `Prescrizione` boolean NULL,
  PRIMARY KEY (`AIC`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Prescrizione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Prescrizione` (
  `CodiceRicetta` VARCHAR(45) NOT NULL,
  `Farmaco` VARCHAR(45) NOT NULL,
  `QuantitàTotale` INT NULL,
  `QuantitàRimanente` INT NULL,
  PRIMARY KEY (`CodiceRicetta`, `Farmaco`),
  INDEX `Farmaco_idx` (`Farmaco` ASC) VISIBLE,
  CONSTRAINT `CodiceRicetta`
    FOREIGN KEY (`CodiceRicetta`)
    REFERENCES `Farmaciadb`.`RicettaMedica` (`CodiceRicetta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Farmaco`
    FOREIGN KEY (`Farmaco`)
    REFERENCES `Farmaciadb`.`Farmaco` (`AIC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;