-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 16:39:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Farmaciadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Farmaciadb` DEFAULT CHARACTER SET utf8 ;
USE `Farmaciadb` ;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`TesseraSanitaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`TesseraSanitaria` (
  `CodiceFiscale` VARCHAR(16) NOT NULL,
   -- CONSTRAINT chk_codice_fiscale CHECK (
   -- `CodiceFiscale` LIKE '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'),
  `Cognome` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `DataScadenza` DATE NOT NULL,
  `DataEmissione` DATE NOT NULL,
  `DataNascita` DATE NOT NULL,
  `NumeroDocumento` VARCHAR(20) NOT NULL UNIQUE,
  PRIMARY KEY (`CodiceFiscale`))	
  ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `Farmaciadb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Cliente` (
  `CodiceTessera` INT NOT NULL,
  `SaldoPunti` INT NOT NULL,
  `Cellulare` VARCHAR(10) NULL, -- si da per scontato che ci sta il +39 davanti
  `Consenso` BOOLEAN NOT NULL,
  `CodiceFiscale` VARCHAR(16) NOT NULL UNIQUE,
  `Email` VARCHAR(45) NULL,
  `Via` VARCHAR(100) NULL,
  `NumeroCivico` VARCHAR(10) NULL,
  `Città` VARCHAR(45) NULL,
  `CAP` VARCHAR(10) NULL,
  PRIMARY KEY (`CodiceTessera`),
  CONSTRAINT `CodiceTessera`
  FOREIGN KEY (`CodiceFiscale`)
	REFERENCES `Farmaciadb`.`TesseraSanitaria` (`CodiceFiscale`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
	ENGINE = InnoDB;
    
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`RicettaMedica` (
  `CodiceRicetta` VARCHAR(45) NOT NULL,
  `DataScadenza` DATE NOT NULL,
  `DataEmissione` DATE NOT NULL,
  `CodiceMedicoDibase` VARCHAR(45) NOT NULL,
  `CodiceFiscale` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`CodiceRicetta`),
  -- INDEX `CodiceFiscale_idx` (`CodiceFiscale` ASC) VISIBLE,
  CONSTRAINT `CodiceFiscale`
  FOREIGN KEY (`CodiceFiscale`)
  REFERENCES `Farmaciadb`.`TesseraSanitaria` (`CodiceFiscale`)
  ON DELETE CASCADE
  ON UPDATE CASCADE
    )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Farmaco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Farmaco` (
  `AIC` VARCHAR(50) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `PrincipioAttivo` VARCHAR(45) NOT NULL,
  `PrezzoUnitario` DECIMAL(10,2) NOT NULL CHECK (`PrezzoUnitario` > 0),
  `Dosaggio` DECIMAL(10,2) NOT NULL CHECK (`Dosaggio` > 0),
  `FormaFarmaceutica` VARCHAR(45) NOT NULL,
  `Prescrizione` BOOLEAN NOT NULL,
  PRIMARY KEY (`AIC`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Prescrizione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Prescrizione` (
  `CodiceRicetta` VARCHAR(45) NOT NULL,
  `Farmaco` VARCHAR(50) NOT NULL,
  `QuantitàTotale` INT NOT NULL,
  `QuantitàRimanente` INT NOT NULL,
  PRIMARY KEY (`CodiceRicetta`, `Farmaco`),
  INDEX `Farmaco_idx` (`Farmaco` ASC) VISIBLE,
  CONSTRAINT `CodiceRicetta`
    FOREIGN KEY (`CodiceRicetta`)
    REFERENCES `Farmaciadb`.`RicettaMedica` (`CodiceRicetta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Farmaco`
    FOREIGN KEY (`Farmaco`)
    REFERENCES `Farmaciadb`.`Farmaco` (`AIC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Allergene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Allergene` (
  `Nome` VARCHAR(45) NOT NULL,
  `Descrizione` LONGTEXT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Presenza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Presenza` (
  `Farmaco` VARCHAR(45) NOT NULL,
  `Allergene` VARCHAR(45) NOT NULL,
  `InfoAggiuntive` LONGTEXT NULL,
  PRIMARY KEY (`Farmaco`, `Allergene`),
  CONSTRAINT `PFarmaco`
    FOREIGN KEY (`Farmaco`)
    REFERENCES `Farmaciadb`.`Farmaco` (`AIC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Allergene`
    FOREIGN KEY (`Allergene`)
    REFERENCES `Farmaciadb`.`Allergene` (`Nome`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Lotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Lotto` (
  `CodiceLotto` VARCHAR(45) NOT NULL,
  `Farmaco` VARCHAR(45) NOT NULL ,
  `QuantitàDisponibile` INT NOT NULL CHECK (`QuantitàDisponibile` >= 0),
  PRIMARY KEY (`CodiceLotto`,`Farmaco`),
  INDEX `Farmaco_idx` (`Farmaco` ASC) VISIBLE,
  CONSTRAINT `FKFarmaco`
    FOREIGN KEY (`Farmaco`)
    REFERENCES `Farmaciadb`.`Farmaco` (`AIC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Cassa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Cassa` (
  `IdCassa` INT NOT NULL,
  `ContanteDisponibile` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`IdCassa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmaciadb`.`Vendita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Vendita` (
  `IdVendita` INT NOT NULL,
  `DataVendita` DATE NOT NULL,
  `OraVendita` TIME NOT NULL,
  `MetodoDiPagamento` VARCHAR(45) NOT NULL,
  `IdCassa` INT NOT NULL,
  PRIMARY KEY (`IdVendita`, `DataVendita`),
  CONSTRAINT `IdCassa`
    FOREIGN KEY (`IdCassa`)
    REFERENCES `Farmaciadb`.`Cassa` (`IdCassa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Ruolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Ruolo` (
  `NomeQualifica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NomeQualifica`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Dipendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Dipendente` (
  `CodiceFiscale` VARCHAR(16) NOT NULL,
  `DataNascita` DATE NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `DataAssunzione` DATE NOT NULL,
  `DataScadenzaContratto` DATE NOT NULL,
  `DataIncarico` DATE NOT NULL,
  `Ruolo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodiceFiscale`),
  INDEX `Ruolo_idx` (`Ruolo` ASC) VISIBLE, -- non so che fa 
  CONSTRAINT `Ruolo`
    FOREIGN KEY (`Ruolo`)
    REFERENCES `Farmaciadb`.`Ruolo` (`NomeQualifica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`TurnoLavorativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`TurnoLavorativo` (
  `Dipendente` VARCHAR(16) NOT NULL,
  `Data` DATE NOT NULL,
  `OraInizio` TIME NOT NULL,
  `OraFine` TIME NOT NULL,
  PRIMARY KEY (`Dipendente`, `Data`),
  CONSTRAINT `Dipendente`
    FOREIGN KEY (`Dipendente`)
    REFERENCES `Farmaciadb`.`Dipendente` (`CodiceFiscale`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`TurnoCassa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`TurnoCassa` (
  `Dipendente` VARCHAR(16) NOT NULL,
  `Data` DATE NOT NULL,
  `OraInizio` TIME NOT NULL,
  `OraFine` TIME NOT NULL,
  `Cassa` INT NOT NULL, 
  PRIMARY KEY (`Dipendente`, `Data`, `OraInizio`),
  CONSTRAINT `TDipendente`
    FOREIGN KEY (`Dipendente`)
    REFERENCES `Farmaciadb`.`Dipendente` (`CodiceFiscale`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
	CONSTRAINT `FKCassa`
	FOREIGN KEY (`Cassa`)
    REFERENCES `Farmaciadb`.`Cassa` (`Idcassa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Fornitore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Fornitore` (
  `PIva` VARCHAR(11) NOT NULL CHECK (LENGTH(`PIva`) = 11 ),
  `NomeAzienda` VARCHAR(100) NOT NULL,
  `CelluraleTelefonoFisso` VARCHAR(20) NOT NULL,
  `Via` VARCHAR(100) NULL,
  `NumeroCivico` VARCHAR(10) NULL,
  `Cap` VARCHAR(10) NULL,
  PRIMARY KEY (`PIva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmaciadb`.`Ordine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Ordine` (
  `CodiceOrdine` VARCHAR(45) NOT NULL,
  `DataConsegnaEffettiva` DATE NOT NULL,
  `DataConsegnaPrevista` DATE NOT NULL,
  `StatoOrdine` VARCHAR(45) NULL,
  `DataEmissione` DATE NOT NULL,
  `Fornitore` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`CodiceOrdine`),
  INDEX `Fornitore_idx` (`Fornitore` ASC) VISIBLE,
  CONSTRAINT `Fornitore`
    FOREIGN KEY (`Fornitore`)
    REFERENCES `Farmaciadb`.`Fornitore` (`PIva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmaciadb`.`Acquisto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Acquisto` (
  `Vendita` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Ricetta` VARCHAR(45) NULL,
  `Lotto` VARCHAR(45) NOT NULL,
  `Farmaco` VARCHAR(45) NOT NULL,
  `NumeroDiSerie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Lotto`, `Farmaco`, `NumeroDiSerie`),
  INDEX `Ricetta_idx` (`Ricetta` ASC) VISIBLE,
  INDEX `Lotto_idx` (`Lotto` ASC) VISIBLE,
  INDEX `Farmaco_idx` (`Farmaco` ASC) VISIBLE,
  INDEX `Data_idx` (`Data` ASC) VISIBLE,
    CONSTRAINT `FKVendita`
    FOREIGN KEY (`Vendita`,`Data`)
    REFERENCES `Farmaciadb`.`Vendita` (`IdVendita`,`DataVendita`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Ricetta`
    FOREIGN KEY (`Ricetta`)
    REFERENCES `Farmaciadb`.`RicettaMedica` (`CodiceRicetta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Lotto`
    FOREIGN KEY (`Lotto`,`Farmaco`)
    REFERENCES `Farmaciadb`.`Lotto` (`CodiceLotto`,`Farmaco`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Farmaciadb`.`Riferimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmaciadb`.`Riferimento` (
  `Lotto` VARCHAR(45) NOT NULL,
  `Farmaco` VARCHAR(45) NOT NULL,
  `Ordine` VARCHAR(45) NOT NULL,
  `QuantitàOrdinata` INT NOT NULL CHECK (`QuantitàOrdinata` > 0 ),
  PRIMARY KEY (`Lotto`, `Farmaco`, `Ordine`),
  INDEX `Farmaco_idx` (`Farmaco` ASC) VISIBLE,
  INDEX `Ordine_idx` (`Ordine` ASC) VISIBLE,
  CONSTRAINT `FKRLotto`
    FOREIGN KEY (`Lotto`,`Farmaco`)
    REFERENCES `Farmaciadb`.`Lotto` (`CodiceLotto`,`Farmaco`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Ordine`
    FOREIGN KEY (`Ordine`)
    REFERENCES `Farmaciadb`.`Ordine` (`CodiceOrdine`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


